Repository SUB-Meet/submeet-backend, pull requests merged in 2024-03, with the labels that each got.

#3 ✨ Feat : CI/CD 파이프라인 구축
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
Labels: :construction_worker_man: CICD, :sparkles: Feature

#4 👷 [CI/CD] Health check 추가
  build.gradle
  src/main/java/submeet/backend/web/controller/RootController.java
Labels: :construction_worker_man: CICD

#7 feat : 멤버 컨트롤러 추가
  src/main/java/submeet/backend/web/controller/RootController.java
Labels: :sparkles: Feature

#9 8 feat 엔티티 구성
  build.gradle
  src/main/java/submeet/backend/BackendApplication.java
  src/main/java/submeet/backend/entity/Chat.java
  src/main/java/submeet/backend/entity/Member.java
  src/main/java/submeet/backend/entity/Member_chat.java
  src/main/java/submeet/backend/entity/Post.java
  src/main/java/submeet/backend/entity/Station.java
  src/main/java/submeet/backend/entity/common/BaseEntity.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :sparkles: Feature

#11 Feat/10 : 회원가입 기능 개발
  build.gradle
  src/main/java/submeet/backend/config/SwaggerConfig.java
  src/main/java/submeet/backend/converter/MemberConverter.java
  src/main/java/submeet/backend/repository/member/MemberRepository.java
  src/main/java/submeet/backend/service/member/MemberService.java
  src/main/java/submeet/backend/service/member/MemberServiceImpl.java
  src/main/java/submeet/backend/web/controller/MemberController.java
  src/main/java/submeet/backend/web/dto/member/MemberRequestDTO.java
  src/main/java/submeet/backend/web/dto/member/MemberResponseDTO.java
Labels: :sparkles: Feature
